server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Enrutamiento hacia el Microservicio de Autenticación
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        # Enrutamiento hacia el Microservicio de Usuarios
        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/api/usuarios/**

        # Enrutamiento hacia el Microservicio de Productos
        - id: product-route
          uri: lb://product-service
          predicates:
            - Path=/api/productos/**

        # Enrutamiento hacia el Microservicio de Inventario
        - id: inventory-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventario/**

        # Enrutamiento hacia el Microservicio de Órdenes
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/api/ordenes/**

        # Enrutamiento hacia el Microservicio de Pagos
        - id: payment-route
          uri: lb://payment-service
          predicates:
            - Path=/api/pagos/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true