# Puerto para este servicio (así no choca con los otros de ayer)
server.port=8084

# Conexión limpia a Laragon (Crea la base de datos sola si no existe)
spring.datasource.url=jdbc:mysql://localhost:3306/gamehub_categories?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Muestra las consultas en consola y maneja las tablas de forma automática
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true